#!/usr/bin/env python3
"""Collect the figures used by the paper into a single directory."""

from __future__ import annotations

import shutil
from pathlib import Path


THIS_DIR = Path(__file__).resolve().parent
ANALYSIS_DIR = THIS_DIR.parent
SOURCE_DIR = ANALYSIS_DIR / "ml" / "models" / "xgboost_bdt_v6" / "plots"
TARGET_DIR = THIS_DIR / "figs"

FIGURE_STEMS = [
    "analysis_workflow",
    "feynman_diagram",
    "pairing_validation",
    "roc_curve",
    "d34_distribution",
    "fit_templates",
    "bdt_cut_scan",
]

APPENDIX_WIDE_PLOTS = [
    "cutFlow",
]

APPENDIX_PAIRED_PLOTS = [
    "deltaZ_shape",
    "Wstar_m_shape",
    "recoil_m_afterZ_norm",
    "Hcand_m_final_norm",
    "cosTheta_miss_shape",
    "visibleEnergy_shape",
]

APPENDIX_PLOT_STEMS = [*APPENDIX_WIDE_PLOTS, *APPENDIX_PAIRED_PLOTS]

PLOT_LABELS = {
    "cutFlow": "Stacked cutflow yields",
    "cosTheta_miss": r"$|\cos\theta_{\mathrm{miss}}|$",
    "visibleEnergy": "Visible energy excluding the selected lepton",
    "Wstar_m": "Reconstructed hadronic W* candidate mass",
    "Hcand_m_final": "Reconstructed Higgs-candidate mass after the final recoil cut",
    "recoil_m_afterZ": "Recoil mass after the Z-mass cut",
    "deltaZ": r"$|m_{jj}-m_Z|$ from the Z-priority pairing",
}


def caption_for_plot(stem: str) -> str:
    if stem == "cutFlow":
        return "Stacked event yields across the sequential event selection."
    if stem == "deltaZ_shape":
        return r"Unit-area comparison of $|m_{jj}-m_Z|$, showing how the Z-priority pairing concentrates the signal near the on-shell Z mass."
    if stem == "Wstar_m_shape":
        return r"Unit-area comparison of the reconstructed $W^*$ mass, illustrating the broad off-shell signal structure relative to the diboson backgrounds."
    if stem == "recoil_m_afterZ_norm":
        return "Unit-area recoil-mass comparison after the Z-mass requirement, highlighting the Higgs recoil peak used in the final event selection."
    if stem == "Hcand_m_final_norm":
        return "Unit-area Higgs-candidate mass comparison after the final recoil selection."
    if stem == "cosTheta_miss_shape":
        return r"Signal-versus-diboson shape comparison of $|\cos\theta_{\mathrm{miss}}|$, which helps suppress forward missing-momentum topologies."
    if stem == "visibleEnergy_shape":
        return "Signal-versus-diboson comparison of the visible energy excluding the selected lepton, probing the semi-leptonic event balance."
    raise KeyError(f"Unsupported appendix plot stem: {stem}")


def write_appendix_tex(tex_path: Path) -> None:
    lines: list[str] = []
    lines.append("% Auto-generated by paper/sync_paper_figures.py")
    lines.append(r"\clearpage")

    for stem in APPENDIX_WIDE_PLOTS:
        lines.append(r"\begin{figure}[p]")
        lines.append(r"  \centering")
        lines.append(rf"  \includegraphics[width=0.92\textwidth]{{figs/plots_lvqq/{stem}.pdf}}")
        lines.append(rf"  \caption{{{caption_for_plot(stem)}}}")
        lines.append(rf"  \label{{fig:appendix:{stem}}}")
        lines.append(r"\end{figure}")
        lines.append("")

    paired = list(APPENDIX_PAIRED_PLOTS)
    for idx in range(0, len(paired), 2):
        left = paired[idx]
        right = paired[idx + 1] if idx + 1 < len(paired) else None
        lines.append(r"\begin{figure}[p]")
        lines.append(r"  \centering")
        lines.append(r"  \begin{minipage}[t]{0.48\textwidth}")
        lines.append(r"    \centering")
        lines.append(rf"    \includegraphics[width=\textwidth]{{figs/plots_lvqq/{left}.pdf}}")
        lines.append(rf"    \par\smallskip{{\footnotesize {caption_for_plot(left)}}}")
        lines.append(r"  \end{minipage}")
        if right is not None:
            lines.append(r"  \hfill")
            lines.append(r"  \begin{minipage}[t]{0.48\textwidth}")
            lines.append(r"    \centering")
            lines.append(rf"    \includegraphics[width=\textwidth]{{figs/plots_lvqq/{right}.pdf}}")
            lines.append(rf"    \par\smallskip{{\footnotesize {caption_for_plot(right)}}}")
            lines.append(r"  \end{minipage}")
        lines.append(r"\end{figure}")
        lines.append("")

    tex_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    appendix_dir = TARGET_DIR / "plots_lvqq"
    appendix_dir.mkdir(parents=True, exist_ok=True)

    wanted_root_files = {f"{stem}{ext}" for stem in FIGURE_STEMS for ext in (".pdf", ".png")}
    for path in TARGET_DIR.iterdir():
        if path.is_file() and path.name not in wanted_root_files:
            path.unlink()

    wanted_appendix_files = {f"{stem}.pdf" for stem in APPENDIX_PLOT_STEMS}
    for path in appendix_dir.glob("*.pdf"):
        if path.name not in wanted_appendix_files:
            path.unlink()

    missing: list[str] = []
    for stem in FIGURE_STEMS:
        for ext in (".pdf", ".png"):
            src = SOURCE_DIR / f"{stem}{ext}"
            dst = TARGET_DIR / src.name
            if src.exists():
                shutil.copy2(src, dst)
            elif ext == ".pdf":
                missing.append(src.name)

    appendix_source_dir = ANALYSIS_DIR / "plots_lvqq"
    for stem in APPENDIX_PLOT_STEMS:
        src = appendix_source_dir / f"{stem}.pdf"
        dst = appendix_dir / src.name
        if src.exists():
            shutil.copy2(src, dst)
        else:
            missing.append(str(src.relative_to(ANALYSIS_DIR)))

    write_appendix_tex(THIS_DIR / "appendix_plots.tex")

    if missing:
        missing_text = ", ".join(sorted(missing))
        raise SystemExit(f"Missing required paper figure(s): {missing_text}")

    print(f"Synced paper figures to {TARGET_DIR}")


if __name__ == "__main__":
    main()
